-- =============================================================================
-- HeroPad — Initial schema (Supabase / Postgres)
-- Migration: 001_initial_schema.sql
-- =============================================================================
-- Conventions:
--   * `auth.users` is Supabase's built-in users table (UUID primary key).
--   * Sensitive tables have RLS enabled; service role bypasses RLS server-side.
--   * Timestamps are TIMESTAMPTZ with `now()` defaults.
-- =============================================================================

create extension if not exists "uuid-ossp";
create extension if not exists "pgcrypto";

-- -----------------------------------------------------------------------------
-- 1. solana_wallets
--    One Solana wallet per user, generated by Privy.
--    `encrypted_private_key` is stored only if Privy hands us the encrypted blob;
--    otherwise this column stays NULL and Privy holds the key.
-- -----------------------------------------------------------------------------
create table if not exists public.solana_wallets (
  user_id               uuid primary key references auth.users(id) on delete cascade,
  public_key            text not null unique,
  encrypted_private_key text,
  created_at            timestamptz not null default now()
);

create index if not exists idx_solana_wallets_pubkey on public.solana_wallets(public_key);

alter table public.solana_wallets enable row level security;

-- A user can read only their own wallet row.
create policy "wallets_owner_select"
  on public.solana_wallets
  for select
  using (auth.uid() = user_id);

-- Inserts/updates happen from the service role only (server-side).
create policy "wallets_service_role_all"
  on public.solana_wallets
  for all
  to service_role
  using (true)
  with check (true);

-- -----------------------------------------------------------------------------
-- 2. characters
--    The catalog of heroes. `vdash_stats` is a flexible jsonb so we can iterate
--    on game balance without schema migrations.
-- -----------------------------------------------------------------------------
create table if not exists public.characters (
  id            uuid primary key default uuid_generate_v4(),
  name          text not null,
  story_text    text,
  asset_folder  text,
  rarity        text not null check (rarity in ('common','rare','epic','legendary')),
  vdash_stats   jsonb not null default '{}'::jsonb,
  created_at    timestamptz not null default now()
);

create index if not exists idx_characters_rarity on public.characters(rarity);

-- Public read; writes are admin-only (no RLS = forbidden by default for anon when
-- using anon key; we explicitly allow public read).
alter table public.characters enable row level security;
create policy "characters_public_read"
  on public.characters
  for select
  to anon, authenticated
  using (true);

-- -----------------------------------------------------------------------------
-- 3. collectibles_catalog
--    Every physical artefact (figurine / card / packaging) gets a unique code.
--    The code is what gets encoded in NFC or QR.
-- -----------------------------------------------------------------------------
create table if not exists public.collectibles_catalog (
  code                  text primary key,
  type                  text not null check (type in ('figurine_nfc','card_qr','pack_qr')),
  character_id          uuid references public.characters(id) on delete set null,
  signature             text not null,
  cnft_template         jsonb not null default '{}'::jsonb,
  distribution_channel  text not null check (distribution_channel in ('b2c_shopify','b2b_social','event','other')),
  shopify_order_id      text,
  batch_id              text,
  created_at            timestamptz not null default now()
);

create index if not exists idx_catalog_character on public.collectibles_catalog(character_id);
create index if not exists idx_catalog_batch on public.collectibles_catalog(batch_id);

-- Reads happen server-side only; clients never query this table directly.
alter table public.collectibles_catalog enable row level security;
create policy "catalog_service_role_all"
  on public.collectibles_catalog
  for all
  to service_role
  using (true)
  with check (true);

-- -----------------------------------------------------------------------------
-- 4. claims
--    A row per successful claim. Unique on `code` so a code can be claimed once.
-- -----------------------------------------------------------------------------
create table if not exists public.claims (
  id                  uuid primary key default uuid_generate_v4(),
  code                text not null references public.collectibles_catalog(code) on delete restrict,
  claimed_by_user     uuid not null references auth.users(id) on delete cascade,
  cnft_mint_address   text,
  device_id           text,
  scan_method         text not null check (scan_method in ('nfc','qr_card','qr_pack')),
  claimed_at          timestamptz not null default now(),
  constraint claims_code_unique unique (code)
);

create index if not exists idx_claims_user on public.claims(claimed_by_user);
create index if not exists idx_claims_mint on public.claims(cnft_mint_address);

alter table public.claims enable row level security;

-- A user can read only their own claims.
create policy "claims_owner_select"
  on public.claims
  for select
  using (auth.uid() = claimed_by_user);

-- Inserts go through service role.
create policy "claims_service_role_all"
  on public.claims
  for all
  to service_role
  using (true)
  with check (true);

-- -----------------------------------------------------------------------------
-- 5. bits_balance
--    Materialized current balance (kept in sync via bits_transactions or trigger).
-- -----------------------------------------------------------------------------
create table if not exists public.bits_balance (
  user_id          uuid primary key references auth.users(id) on delete cascade,
  current_balance  bigint not null default 0,
  total_earned     bigint not null default 0,
  total_spent      bigint not null default 0,
  updated_at       timestamptz not null default now()
);

alter table public.bits_balance enable row level security;

create policy "bits_balance_owner_select"
  on public.bits_balance
  for select
  using (auth.uid() = user_id);

create policy "bits_balance_service_role_all"
  on public.bits_balance
  for all
  to service_role
  using (true)
  with check (true);

-- -----------------------------------------------------------------------------
-- 6. bits_transactions
--    Append-only ledger.
-- -----------------------------------------------------------------------------
create table if not exists public.bits_transactions (
  id          uuid primary key default uuid_generate_v4(),
  user_id     uuid not null references auth.users(id) on delete cascade,
  amount      bigint not null,                                  -- signed: +earn, -spend
  reason      text not null,                                    -- e.g. 'claim','vdash_run','redeem'
  metadata    jsonb not null default '{}'::jsonb,
  created_at  timestamptz not null default now()
);

create index if not exists idx_bits_tx_user on public.bits_transactions(user_id, created_at desc);
create index if not exists idx_bits_tx_reason on public.bits_transactions(reason);

alter table public.bits_transactions enable row level security;

create policy "bits_tx_owner_select"
  on public.bits_transactions
  for select
  using (auth.uid() = user_id);

create policy "bits_tx_service_role_all"
  on public.bits_transactions
  for all
  to service_role
  using (true)
  with check (true);

-- =============================================================================
-- End of 001_initial_schema.sql
-- =============================================================================
